from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml

from mvp_vertical.hermes_distribution import (
    component_content_digest,
    evaluate,
    file_content_digest,
    route_contract,
    tree_content_digest,
)


ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "hermes" / "distribution" / "pantheon-standard.lock.yaml"


def _manifest() -> dict:
    value = yaml.safe_load(LOCK.read_text(encoding="utf-8"))
    assert isinstance(value, dict)
    return value


def _roots(tmp_path: Path) -> dict[str, Path]:
    next_root = tmp_path / "Pantheon-Next"
    next_root.mkdir()
    return {"pantheon-mvp": ROOT, "Pantheon-Next": next_root}


def test_distribution_lock_keeps_exact_core_separate_and_default_off(tmp_path) -> None:
    manifest = _manifest()

    assert evaluate(manifest, repository_roots=_roots(tmp_path)) == []

    required_kinds = {
        item["kind"] for item in manifest["components"] if item["required"] is True
    }
    assert required_kinds == {"run_binding", "context_bridge", "runtime_observer"}
    assert len(manifest["components"]) == 3
    assert all(item["enabled_by_default"] is False for item in manifest["components"])
    assert all(item["content_digest"].startswith("sha256:") for item in manifest["components"])
    assert manifest["source_pins"]["hermes_runtime"]["version"] == "0.19.0"
    assert manifest["source_pins"]["hermes_runtime"]["artifact_digest"] is None
    assert manifest["state"]["activation_state"] == "not_activated"
    assert manifest["state"]["task_authorization_state"] == "not_authorized"
    assert set(manifest["authority"].values()) == {False}


def test_distribution_digest_algorithms_are_deterministic(tmp_path) -> None:
    file_path = tmp_path / "one.txt"
    file_path.write_bytes(b"one\n")
    assert file_content_digest(file_path) == component_content_digest(file_path, "file")

    tree = tmp_path / "tree"
    (tree / "nested").mkdir(parents=True)
    (tree / "b.txt").write_bytes(b"b")
    (tree / "nested" / "a.txt").write_bytes(b"a")
    first = tree_content_digest(tree)
    second = tree_content_digest(tree)
    assert first == second
    assert first == component_content_digest(tree, "tree")

    cache = tree / "__pycache__"
    cache.mkdir()
    (cache / "tools.cpython-311.pyc").write_bytes(b"generated bytecode")
    (tree / "generated.pyo").write_bytes(b"generated optimized bytecode")
    (tree / ".DS_Store").write_bytes(b"generated metadata")
    assert tree_content_digest(tree) == first

    (tree / "nested" / "a.txt").write_bytes(b"changed")
    assert tree_content_digest(tree) != first


def test_distribution_route_contract_matches_current_adapter_sources(tmp_path) -> None:
    assert route_contract(_manifest(), _roots(tmp_path)) == []


def test_distribution_validator_rejects_digest_authority_and_default_enablement(tmp_path) -> None:
    manifest = _manifest()
    invalid = deepcopy(manifest)
    invalid["components"][0]["content_digest"] = "sha256:" + "0" * 64
    invalid["components"][0]["enabled_by_default"] = True
    invalid["state"]["activation_state"] = "activated"
    invalid["authority"]["dispatches_runs"] = True

    errors = evaluate(invalid, repository_roots=_roots(tmp_path))

    assert any(error.startswith("component run-binding digest mismatch:") for error in errors)
    assert "component must remain default-off: run-binding" in errors
    assert "distribution lock must not activate a binding" in errors
    assert "distribution lock claims authority: dispatches_runs" in errors
