-- B3 extension of the existing B1 direct human access seam.
--
-- This migration adds one bounded technical action for document discussion.
-- It does not create professional review, approval, decision or project-role
-- authority. Existing grants and provenance remain unchanged.

DO $$
DECLARE
    constraint_row RECORD;
BEGIN
    -- 030 predates document.comment. Drop only the two old CHECK constraints
    -- whose definitions contain document.revision.submit but not the new action.
    -- Constraint names were generated by PostgreSQL, so identify them by their
    -- actual definition rather than assuming generated names.
    FOR constraint_row IN
        SELECT conname, pg_get_constraintdef(oid) AS definition
          FROM pg_constraint
         WHERE conrelid = 'human_resource_grants'::regclass
           AND contype = 'c'
    LOOP
        IF constraint_row.definition LIKE '%document.revision.submit%'
           AND constraint_row.definition NOT LIKE '%document.comment%' THEN
            EXECUTE format(
                'ALTER TABLE human_resource_grants DROP CONSTRAINT %I',
                constraint_row.conname
            );
        END IF;
    END LOOP;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'human_resource_grants_action_allowed_check'
           AND conrelid = 'human_resource_grants'::regclass
    ) THEN
        ALTER TABLE human_resource_grants
            ADD CONSTRAINT human_resource_grants_action_allowed_check
            CHECK (action IN (
                'project.read',
                'document.read',
                'document.revision.submit',
                'document.comment'
            ));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'human_resource_grants_target_action_check'
           AND conrelid = 'human_resource_grants'::regclass
    ) THEN
        ALTER TABLE human_resource_grants
            ADD CONSTRAINT human_resource_grants_target_action_check
            CHECK (
                (resource_type = 'project'
                 AND resource_id = project_id
                 AND action = 'project.read')
                OR
                (resource_type = 'project_document'
                 AND action IN (
                     'document.read',
                     'document.revision.submit',
                     'document.comment'
                 ))
            );
    END IF;
END;
$$;

COMMENT ON CONSTRAINT human_resource_grants_action_allowed_check
    ON human_resource_grants IS
    'Closed technical action vocabulary. document.comment permits discussion only and confers no review, approval or decision authority.';
